name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install numpy
      run: pip install --upgrade numpy
    - name: Compile
      run: g++ -c -Wall -O2 -Wall -ansi -pedantic -fPIC -o manana.o src/manana.cpp
    - name: Shared Library
      run: g++ -o libmanana.so -shared manana.o
    - name: Copy Shared Library to Robot Directory
      run: cp libmanana.* tests
    - name: Create reports folder
      run: mkdir -p reports
    - name: List files
      run: ls tests
    - name: Present Working Directory
      run: pwd
    - name: Run Robot Framework Tests
      run: |
        docker run \
          -v ${PWD}/reports:/opt/robotframework/reports:Z \
          -v ${PWD}/tests:/opt/robotframework/tests:Z \
          -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
          --user $(id -u):$(id -g) \
          ppodgorsek/robot-framework:latest
    - name: Upload reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: reports
        path: ${{ github.workspace }}/reports
